author: ByeMC
baseurl: ""

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "ByeMC"
      excerpt_separator: "<!--more-->"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
